config/routes.rb
Shoppingcart::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'add' => 'line_items#add'
  post 'subtract' => 'line_items#subtract'
  post 'order' => 'carts#order'
  get 'toggle_edit' => 'items#toggle_edit'
  resources :sessions
  root :to => "items#index"

  resources :users

  resources :line_items

  resources :carts

  resources :items

  get "users/new"

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :user_id, :active
  has_many :line_items

	def get_total_items
		total = 0
		self.line_items.each do |item|
			total+=item.quantity
		end
		total
	end

  def merge(old_cart)
    old_cart.line_items.each do |item|
      @LineItem = LineItem.where(:item_id => item.item.id, :cart_id => self.id).first_or_create
      if @LineItem.new_record?
        @LineItem.quantity = item.quantity
      else 
        if @LineItem.quantity.nil?
          @LineItem.quantity = 0
        end
        @LineItem.quantity += item.quantity
      end
      @LineItem.save
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController


  def order
    @cart = Cart.find(current_cart.id)
    @cart.active = "false"
    @cart.save
    session[:cart_id] = nil
    redirect_to items_path
  end

  def index
    @carts = Cart.where(:active => false)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<div class="center hero-unit">
<h1>Listing carts</h1>

<table class="table table-striped">
  <tr>
    <th>Order ID</th>
    <th>Buyer Name</th>
    <th>Buyer ID</th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%=cart.id%></td>
    <td><%=User.find(cart.user_id).first_name%></td>
    <td><%=cart.user_id%></td>
    <td><%= link_to 'Show', cart %></td>
  </tr>
<% end %>
</table>

<br />

</div>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="center hero-unit">
  <% if flash[:notice] %>
      <p class="alert"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:error] %>
      <p class="error"><%= flash[:error] %></p>
    <% end %>
<h3>Cart</h3>
<%total_price = 0%>
<%quantity=0%>
<table class="table table-striped">
  <tr>
    <th>Item</th>
    <th>Description</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Total Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @cart.line_items.each do |item| %>
	<% total_price += item.item.price*item.quantity %>
	<%quantity+=item.quantity%>
	<tr>
		<td><%= item.item.name %></td>
		<td><%= item.item.description %></td>
		<td><%= sprintf("$%0.02f", item.item.price) %></td>
		<td><%= item.quantity %></td>
		<td><%=sprintf("$%0.02f",item.quantity * item.item.price) %>
		<td> 
			<%= link_to(add_path(item_id: item.item.id), method: :post, :class => 'btn btn-success	') do %>
				<%= content_tag('i', nil, class: 'icon-plus-sign') %>
			<%end%>
		</td>
		<td>
			<% visibility = item.quantity>1 ? "visible" : "hidden" %>
	      	<%= link_to(subtract_path(item_id: item.item.id), method: :post,class: 'btn btn-warning', style:"visibility:"+visibility+";") do %>
				<%= content_tag('i', nil, class: 'icon-minus-sign') %>
			<% end %>
		</td>
		<td>
			<%= link_to(line_item_path(item_id: item.item.id, cart_id: @cart.id), method: :delete, :class => 'btn btn-danger	') do %>
				<%= content_tag('i', nil, class: 'icon-remove-sign') %>
			<%end%>
		</td>
	</tr>
<% end %>
	<tr>
		<td></td>
		<td></td>
		<td></td>
		<td><strong><%=quantity%></strong></td>
		<td><strong><%=sprintf("$%0.02f",total_price)%></strong></td>
		<td colspan="3">
      		<%= button_to 'Order', order_path(:cart_id => @cart.id), method: :post, :class=>"btn btn-primary" %>
    	</td>
	</tr>
</table>

<br />

<!--<%= link_to 'New Item', new_item_path %>-->
</div>