config/routes.rb
Shoppingcart::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'add' => 'line_items#add'
  post 'subtract' => 'line_items#subtract'
  post 'order' => 'carts#order'
  get 'toggle_edit' => 'items#toggle_edit'
  resources :sessions
  root :to => "items#index"

  resources :users

  resources :line_items

  resources :carts

  resources :items

  get "users/new"

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :price, :description
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authorize, only: [:edit, :update, :new, :create]
  # GET /items
  # GET /items.json

  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  def toggle_edit
    if session[:edit]
      session[:edit] = false
    else
      session[:edit] = true
    end
    redirect_to items_url
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end


  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])
    
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="center hero-unit">
  <% if flash[:notice] %>
      <p class="alert" style="display:inline; text-align:center; "><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:error] %>
      <p class="error"><%= flash[:error] %></p>
    <% end %>
<h1>Catalogue</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= sprintf("$%0.02f", item.price) %></td>
    <td><%= item.description %></td>
    <% if !session[:edit]%>
    <td colspan="3">
      <%= button_to 'Add to Cart', add_path(:item_id => item.id), :class=>"btn btn-primary" %>
    </td>
    <% else %>
    <td><%= button_to 'Show', item, :class=>"btn btn-success btn-mini" %></td>
    <td><%= button_to 'Edit', edit_item_path(item), :class=>"btn btn-warning btn-mini" %></td>
    <td><%= button_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-mini" %></td>


    <% end %>
  </tr>
<% end %>
</table>

<br />
<%if session[:edit]%>
<%= link_to 'New Item', new_item_path %>
<%end%>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>