config/routes.rb
Shoppingcart::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'add' => 'line_items#add'
  post 'subtract' => 'line_items#subtract'
  post 'order' => 'carts#order'
  get 'toggle_edit' => 'items#toggle_edit'
  resources :sessions
  root :to => "items#index"

  resources :users

  resources :line_items

  resources :carts

  resources :items

  get "users/new"

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
          <div class="container">
       
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>

            <a class="brand" href="/">Shopping Cart App</a>
       
            
            <h5 style="color:white; margin-left:10px; margin-top:13px;"class="pull-right">

                Hello <%= current_user.first_name %>.
              <% if current_user && !current_user.temp %>

                <%= link_to "Log Out", logout_path, :class => 'nav_bar_link' %>
              <% else %>
                <%= link_to "Sign up", new_user_path, :class => 'nav_bar_link' %> or 
                <%= link_to "Log in", new_session_path, :class => 'nav_bar_link' %>
              <% end %>
            </h5>
            
              <% if seller %>
                  <h5 style="color:white; margin-left:10px; margin-top:13px;"class="pull-right">
                  <%if !session[:edit]%>
                    <%= link_to "View Orders | ", carts_path, :class => 'nav_bar_link' %>
                    <%= link_to "Switch to Sell mode | ", toggle_edit_path, :class => 'nav_bar_link' %>
                  <%else%>
                  <%= link_to "Switch to Buy mode |", toggle_edit_path, :class => 'nav_bar_link' %>
                  <%end%>
                  </h5>
                <%end%>
              <%if !session[:edit]%>
              <%= link_to "Cart: " + current_cart.get_total_items.to_s + " items", current_cart, :class => 'btn btn-inverse', :style => 'color:white;' %>
              <%end%>

          </div>
        </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>
  <body>

    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%=current_cart.id%>
  </body>
</html>